
# C integer binding
class CInt():
    def __del__(self): ...
    def getvalue(self) -> int: ...

class CppMap():
    def __del__(self): ...
    def put(self, key: object, value: object) -> None: ...
    def get(self, key: object) -> object: ...
    def __init__(self, compare_func: object): ...
    def __getitem__(self, key: object) -> object: ...
    def __setitem__(self, key: object, value: object) -> None: ...

class MethodWrapper():
    def __call__(self, *args, **kwargs) -> object: ...

def CInt_New() -> CInt: ...
def CInt_FromInt(value: int) -> CInt: ...
