def myadd(a: int, b: int) -> int: ...
def mysum(*args: int) -> int: ...
def mysum_vec(*args: int) -> int: ...
def kwarg_names(*args: object, **kwargs: object) -> list[str]: ...
def len_args_kwargs(*args: object, **kwargs: object) -> tuple[int, int]: ...
