#!/usr/bin/sh
# Generate a single-file header for cppbind. Instead of distributing
# the include/ directory, we can just distribute cppbind-sys.h, which contains
# all the necessary system headers and cppbind itself.
set -ex

test -d include || {
    echo "Error: include/ directory not found."
    exit 1
}

cd include

# detect system headers.
echo '' > cppbind-sys.h
find . -name \*.h -print0 | xargs -0 cat | grep -E '#include <(.+)>' | sort | uniq > ./sys.inc

# Perform copy-paste preprocessing to resolve all #include "..." 
# directives in cppbind.h and its dependencies.
cat << EOF | python3 > cppbind.inc
import re

processed = set()
include_pattern = re.compile(r'#include\s+"(.+)"')
sys_include_pattern = re.compile(r'#include\s+<(.+)>')

def preprocess(ifile: str):
    if ifile in processed:
        return
    processed.add(ifile)
    header_def = '__' + ifile.replace('/', '_').replace('.', '_').upper() + '__'
    exclude_stmts = [f'#ifndef {header_def}',
                     f'#define {header_def} (1)',
                     f'#endif /* {header_def} */']
    last_exclude_stmt = 0
    with open(ifile, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        for line in lines:
            stripped = line.rstrip()
            if exclude_stmts[last_exclude_stmt] == stripped:
                last_exclude_stmt += 1
                if last_exclude_stmt == len(exclude_stmts):
                    print('\n')
                    break
                continue
            if re.match(sys_include_pattern, line):
                pass
            elif m := re.match(include_pattern, line):
                preprocess(m.group(1))
            else:
                print(line, end='')

# cppbind.h is the main header that includes all other headers.
if __name__ == '__main__':
    preprocess('cppbind.h')
EOF

# Generate the final header.
cat << EOF > cppbind-sys.h
#ifndef __CPPBIND_SYS_H__
#define __CPPBIND_SYS_H__ (1)

/**
 * Auto-generated (amalgamation) header of cppbind.
 * DO NOT EDIT THIS FILE MANUALLY. Instead, edit the source files in
 * include/cppbind/ and run script/gen-hdr.sh to regenerate this file.
 */

#include <Python.h>

EOF

{
  grep -v 'gtest' < sys.inc 
  cat < cppbind.inc         
  echo '#endif /* __CPPBIND_SYS_H__ */'
} >> cppbind-sys.h

rm -f sys.inc cppbind.inc || true

# finally, format the generated header.
cd ..
clang-format -i include/cppbind-sys.h

exit 0
